NewsStudyRtk/NewsStudyRtk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views as main_views

handler404 = main_views.custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug/__', include(debug_toolbar.urls)),
    ]+ urlpatterns

    urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель ночного сайта"
admin.site.index_title = "Новости DIXIE"

NewsStudyRtk/main/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='of'),
    path('contacts/', views.contacts, name='contact'),
    path('offer/', views.offer, name='action'),
    path('demoform/',views.demoform),
    path('showlastmodel/',views.showlastmodel),
    path('', views.index, name='demo'),
]

NewsStudyRtk/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('private/', views.index, name='user_index'),
    path('private/update', views.profile_update, name='profile_update'),
    path('contact_page', views.contact_page, name='contact_page'),
    path('registration',views.registration,name='registration'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password', views.password_update, name='password'),
    path('favorites/<int:id>', views.add_to_favorites, name='favorites'),
    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<int:id>/remove/', views.remove_favorite, name='remove_favorite'),
    path('mynewslist',views.my_news_list,name='my_news_list'),
]

NewsStudyRtk/news/models.py
from ckeditor.fields import RichTextField
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.core.validators import MinLengthValidator

class Tag(models.Model):
    title = models.CharField(max_length=80)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title','status']
        verbose_name= 'Тэг'
        verbose_name_plural='Тэги'


class PublishedToday(models.Manager):
    def get_queryset(self):
        return super(PublishedToday,self).get_queryset().filter(date__gte=datetime.date.today())

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=1)

class Article(models.Model):
    #title = models.CharField(max_length=30)

    categories = (('E','Economics'),
                  ('S','Science'),
                  ('IT','IT'))
    #поля                           #models.CASCADE SET_DEFAULT
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField('Название',max_length=30,default='')
    anouncement = models.TextField('Аннотация',max_length=50)
    #text = models.TextField('Текст новости')
    source = models.URLField('Источник', null=True)
    sourcename = models.CharField('Название источника', max_length=15, validators=[MinLengthValidator(2)], null=False)
    text = RichTextField('Текст новости', validators=[MinLengthValidator(50)], null=False)
    date = models.DateTimeField('Дата публикации',auto_now=True)
    category = models.CharField(choices=categories, max_length=20,verbose_name='Категории')
    #image = models.ImageField(blank=True, upload_to='images/')
    tags = models.ManyToManyField(to=Tag, blank=True)
    #slug = models.SlugField()
    status = models.BooleanField(default=False, verbose_name='Опубликовано')
    objects = models.Manager()
    published = PublishedManager()

    #методы моделей
    def __str__(self):
        return f'{self.title} от: {str(self.date)[:16]}'

    def get_absolute_url(self):
        return f'/news/show/{self.id}'

    def tag_list(self):
        s = ''
        for t in self.tags.all():
            s += t.title + ' '
        return s

    def image_tag(self):
        image = Image.objects.filter(article=self)
        if image:
            return mark_safe(f'<img src="{image[0].image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'

    def get_absolute_url_public(self):
        return f'/news/show/public/{self.author_id}'
    #метаданные модели

    def get_views(self):
        return self.views.count()

    class Meta:
        ordering = ['title','date']
        verbose_name= 'Новость'
        verbose_name_plural='Новости'


class Subscriber(models.Model):
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', default='', null=False)
    first_name = models.CharField(max_length=50, verbose_name='Имя', default='', null=False)
    email = models.EmailField(max_length=254, verbose_name='Адрес электронной почты', null=False)

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.email}"

    class Meta:
        ordering = ['last_name']
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

class Image(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(upload_to='article_images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image is not None:
            return mark_safe(f'<img src="{self.image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'

class ViewCount(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,
                                related_name='views', verbose_name='Новость')
    ip_address = models.GenericIPAddressField(verbose_name='ip-адрес')
    view_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')

    class Meta:
        verbose_name = 'Счетчик просмотров'
        verbose_name_plural = 'Счетчики просмотров'
        ordering=('-view_date',)
        indexes = [models.Index(fields=['-view_date'])]

    def __str__(self):
        return self.article.title

NewsStudyRtk/users/models.py
from ckeditor.fields import RichTextField
from .validators import russian_email
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import User
from news.models import Article
class Account(models.Model):
    gender_choices= (('M','Male'),
                     ('F','Female'),
                     ('N/A','Not answered'))
    user = models.OneToOneField(User,on_delete=models.CASCADE,
                                primary_key=True)
    nickname = models.CharField(max_length=100,blank=True)
    birthdate = models.DateField(null=True)
    gender = models.CharField(choices=gender_choices,max_length=20)
    account_image = models.ImageField(default='default.jpg',
                                      upload_to='account_images')

    address = models.CharField(max_length=100,blank=True)
    job = models.CharField(max_length=100,blank=True)
    whatsapp = models.CharField(max_length=100, blank=True)
    viber = models.CharField(max_length=100, blank=True)
    twitch = models.CharField(max_length=100,blank=True)
    instagram = models.CharField(max_length=100, blank=True)
    facebook = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    discord = models.CharField(max_length=100, blank=True)
    github = models.CharField(max_length=100, blank=True)
    youtube = models.CharField(max_length=100, blank=True)
    linkedin = models.CharField(max_length=100, blank=True)
    snapchat = models.CharField(max_length=100, blank=True)
    skype = models.CharField(max_length=100, blank=True)
    vk = models.CharField(max_length=100, blank=True)
    telegram = models.CharField(max_length=100,blank=True)
    phone = models.CharField(max_length=20,blank=True)

    def __str__(self):
        return f"{self.user.username}'s account"

    class Meta:
        ordering = ['user']
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class FavoriteArticle(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    article = models.ForeignKey(Article,on_delete=models.SET_NULL,null=True)
    create_at=models.DateTimeField(auto_now_add=True)

class ContactForm(models.Model):
    status = models.BooleanField(default=False, verbose_name='Исправлено')
    name = models.CharField(verbose_name='Имя',max_length=100, validators = [MinLengthValidator(2)], null=False)
    email = models.EmailField(verbose_name='Адрес электронной почты',validators=[russian_email], null=False)
    message = RichTextField(verbose_name='Сообщение', null=False)

    class Meta:
        ordering = ['name']
        verbose_name = 'Форма обратной связи'
        verbose_name_plural = 'Форма обратной связи'

NewsStudyRtk/users/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from news.models import Article
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import Group
from .forms import AccountUpdateForm, UserUpdateForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse
from django.core.paginator import Paginator
import json
import os

# def profile(request):
#     context = dict()
#     return render(request,'users/profile.html',context)
#
# def index(request):
#     user_acc = Account.objects.get(user=request.user)
#     context = {'user_acc': user_acc}
#     return render(request,'users/account.html', context)

def index(request):
    context = dict()
    return render(request,'users/account.html',context)

@login_required
def add_to_favorites(request, id):
    article = Article.objects.get(id=id)
    bookmark = FavoriteArticle.objects.filter(user=request.user.id, article=article)
    if bookmark.exists():
        bookmark.delete()
        status = 'removed'
        messages.warning(request, f"Новость {article.title} удалена из закладок")
    else:
        bookmark = FavoriteArticle.objects.create(user=request.user, article=article)
        status = 'added'
        messages.success(request, f"Новость {article.title} добавлена в закладки")
    response = {
        'status': status,
        'id': id,
    }
    return JsonResponse(response)

def favorites(request):
    favorites = FavoriteArticle.objects.filter(user=request.user).select_related('article')
    p = Paginator(favorites, 5)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    return render(request, 'users/favorites.html', {'favorites': page_obj})

def remove_favorite(request, id):
    favorite = get_object_or_404(FavoriteArticle, pk=id, user=request.user)
    favorite.delete()
    return redirect('favorites')

# def profile_update(request):
#     user = request.user
#     account = Account.objects.get(user=user)
#     if request.method == "POST":
#         user_form = UserUpdateForm(request.POST, instance=user)
#         account_form = AccountUpdateForm(request.POST, request.FILES, instance=account)
#         if user_form.is_valid() and account_form.is_valid():
#             user_form.save()
#             account_form.save()
#             messages.success(request,"Профиль успешно обновлен")
#             return redirect('user_index')
#     else:
#         context = {'account_form':AccountUpdateForm(instance=account),
#                    'user_form':UserUpdateForm(instance=user)}
#     return render(request,'users/edit_profile.html',context)

def profile_update(request):
    user = request.user
    account = Account.objects.get(user=user)
    print(user.account.account_image)
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=user)
        account_form = AccountUpdateForm(request.POST, request.FILES, instance=account)
        existing = account.account_image
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            # Проверяем, является ли текущее изображение равным 'default.jpg'
            if os.path.exists(existing.path) and existing.name != 'default.jpg':
                # Удаляем старое изображение
                os.remove(existing.path)

            messages.success(request, "Профиль успешно обновлен")
            return redirect('user_index')
    else:
        context = {'account_form':AccountUpdateForm(instance=account),
                   'user_form':UserUpdateForm(instance=user)}
    return render(request,'users/edit_profile.html',context)

def password_update(request):
    user = request.user
    form = PasswordChangeForm(user,request.POST)
    if request.method == 'POST':
        if form.is_valid():
            password_info = form.save()
            update_session_auth_hash(request,password_info)
            messages.success(request,'Пароль успешно изменен')
            return redirect('user_index')

    context = {"form": form}
    return render(request,'users/edit_password.html',context)

def registration(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() #появляется новый пользователь

            category = request.POST['account_type']
            if category == 'author':
                group = Group.objects.get(name='Actions Required')
                user.groups.add(group)
            else:
                group = Group.objects.get(name='Reader')
                user.groups.add(group)

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)

            login(request, user)

            # Создание объекта Account
            account = Account.objects.create(user=user)

            messages.success(request,f'{username} был зарегистрирован!')
            return redirect('home')
    else:
        form = UserCreationForm()
    context = {'form':form}
    return render(request,'users/registration.html',context)

# def contact_page(request):
#     if request.method == "POST":
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             print('Сообщение отправлено', form.cleaned_data)
#         else:
#             print(form.errors)
#     else:
#         form = ContactForm()
#         form.name='Любимый клиент'
#     context = {'form': form}
#     return render(request,'users/contact_page.html',context)

def search_auto(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        q = request.GET.get('term','')
        articles = Article.objects.filter(title__icontains=q)
        results =[]
        for a in articles:
            results.append(a.title)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data,mimetype)

def contact_page(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваше сообщение успешно отправлено разработчикам сайта! Благодарим Вас за обратную связь!')
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, 'users/contact_page.html', {'form': form})

def my_news_list(request):
    categories = Article.categories #создали перечень категорий
    author = User.objects.get(id=request.user.id) #создали перечень авторов
    articles = Article.objects.filter(author=author)
    if request.method == "POST":
        selected_category = int(request.POST.get('category_filter'))
        if selected_category != 0: #фильтруем найденные результаты по категориям
            articles = articles.filter(category__icontains=categories[selected_category-1][0])
    else: #если страница открывется впервые
        selected_category = 0
    total = len(articles)
    p = Paginator(articles,1)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {'articles': page_obj, 'total':total,
               'categories':categories,'selected_category': selected_category}

    return render(request,'users/my_news_list.html',context)

def article_favorite_btn(request, id):
    article = Article.objects.get(id=id)
    context = {
        'article': article
    }
    return render(request, 'users/my_news_favorite_btn.html', context)

NewsStudyRtk/users/templates/users/contact_page.html
{% extends 'main/homebase.html' %}
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% block title %} Страница обратной связи {% endblock %}
{% block main %}
    <main class="row" style="background: url({% static 'main/img/рассвет.jpg' %}) no-repeat;  background-size: cover;">
        <div class="col-md-2 side_menu">
            {% block sidebar %} {% include 'main/sidebar.html' %} {% endblock %}
        </div>
        {% block content %}
            <div class="col-md-1"></div>
                <div class="col">
                    <h2 class="text-center"><i class="fa-solid fa-envelope"> Страница обратной связи</i></h2><br>
                    <div class="container-fluid>">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <p class="text-center"><input class="btn btn-success" type="submit" value="Отправить"></p>
                        </form>
                    </div>
                </div>
            <div class="col-md-1"></div>
            <script type="text/javascript" src="{% static 'main/js/jquery-min.js' %}"></script>
            <script type="text/javascript" src="{% static 'main/js/bootstrap.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'main/js/jquery.bxslider.js' %}"></script>
            <script type="text/javascript" src="{% static 'main/js/selectnav.min.js' %}"></script>
            <script type="text/javascript">
                selectnav('nav', {
                    label: 'Меню',
                    nested: true,
                    indent: ''
                });
                selectnav('f_menu', {
                    label: 'Меню',
                    nested: true,
                    indent: ''
                });
                $('.bxslider').bxSlider({
                    mode: 'fade',
                    captions: true
                });
            </script>
            <script src="https://kit.fontawesome.com/b91fb3443a.js" crossorigin="anonymous"></script>
            <script src="https://kit.fontawesome.com/b91fb3443a.js" crossorigin="anonymous"></script>
            <!-- jQuery !-->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
            <!-- jQuery UI !-->
            <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
            <script>
                    $(function() {
                        $("#search_input").autocomplete({
                            source: "search_auto/",
                            select: function (event, ui) { //item selected
                                AutoCompleteSelectHandler(event, ui)
                            },
                            minLength: 2,
                        });
                    });

                  function AutoCompleteSelectHandler(event, ui)
                  {
                    var selectedObj = ui.item;
                  }
            </script>
        {% endblock %}
    </main>
{% endblock %}

NewsStudyRtk/users/templates/users/my_news_list.html
{% extends 'main/homebase.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} Мои статьи {% endblock %}

{% block main%}
    <main class="row" style="background: url({% static 'main/img/rails.gif' %}) no-repeat;  background-size: cover; height: 500vh;">
        <div class="col-md-2 side_menu" style="list-style: none; position: relative; height: auto;">
            {% block sidebar %}
                <h1 class="text-center" style="font-family: Rubik Marker Hatch, cursive, Arial, Helvetica Neue, Helvetica, sans-serif;">Меню</h1>
            <ul class="vstack gap-2" id="main">
                {% block home %}<li class="p-1"><i class="fa-solid fa-house"></i><a href="{% url 'home' %}" style="text-decoration: none; color: #FDCE4B;">&nbspДомой</a></li>{% endblock %}
                {% block news %}<li class="p-1"><i class="fa-solid fa-radio"></i><a href="{% url 'news_index' %}" style="text-decoration: none; color: #FDCE4B;">&nbspНовости</a></li>{% endblock %}
                {% block contacts %}<li class="p-1"><i class="fa-solid fa-address-book"></i><a href="{% url 'contact' %}" style="text-decoration: none; color: #FDCE4B;">&nbspКонтакты</a></li>{% endblock %}
                {% block about %}<li class="p-1"><i class="fa-solid fa-people-group"></i><a href="{% url 'of' %}" style="text-decoration: none; color: #FDCE4B;">&nbspО нас</a></li>{% endblock %}
                {% block readers %}<li class="p-1"><i class="fa-solid fa-user-group"></i><a href="{% url 'news_readers' %}" style="text-decoration: none; color: #FDCE4B;">&nbspНаши гости</a></li>{% endblock %}
                {% block offer %}<li class="p-1"><i class="fa-solid fa-gem"></i><a href="{% url 'action' %}" style="text-decoration: none; color: #FDCE4B;">&nbspАкция</a></li>{% endblock %}
                <li><a href="javascript:window.history.back();" style="text-decoration: none; color: #FDCE4B;"><i class="fa-solid fa-reply"> Назад</i></a></li>
                {% block user %}
                        {% include 'users/user-actions.html' %}
                {% endblock %}
            </ul>
            {% endblock %}
            <div style="height: 13vh;"></div>
        </div>
        {% block content %}
            {% if articles|length  != 0 %}
                <div class="col content_center">
                    <div class="row">
                        <label>
                            <h1> Фильтры: (Всего :{{ total }} результатов) </h1>
                            <form class="d-flex" method="post">
                                {% csrf_token %}
                                <div class="form-group col-4">
                                    <select class="form-select" name="category_filter" style="width:40%">
                                        <option value="0">Все категории</option>
                                        {% for c in categories %}
                                            <option value="{{ forloop.counter }}" {% if selected_category == forloop.counter %} selected {% endif %}> {{ c.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <input type="submit" class="btn btn-success col-3" value="Применить">
                            </form>
                        </label>
                    </div>
                    <br>
                    <div class="row">
                        {% for article in articles %}
                            <div style="position: fixed;">
                                <div class="p-4 p-md-5 rounded " style="background: #00000050;">
                                    <div class="row" style="position: inherit;">
                                        <div class="col-md-{% if article.image_set.all %}6{% else %}12 {% endif %} px-0">
                                            <h1 class="display-6" style="font-family: Rubik Marker Hatch, cursive, Arial, Helvetica Neue, Helvetica, sans-serif;"> {{ article.title }}</h1>
                                            <p class="lead my-3">{{ article.anouncement }}</p>
                                            <p class="lead mb-0"><a href="{% url 'news_detail' article.pk %}" class="text-white fw-bold">Полный текст..</a></p>
                                            <p><small>Просмотры: {{ article.get_views }}</small></p>
                                            <!--кнопка в избранное-->
                                            {% block favoritebtn %}
                                                {% include 'news/favorite_btn.html' %}
                                            {% endblock %}
                                        </div>
                                        {% if article.image_set.all %}
                                            <div class="col-md-6 px-0">
                                                <img src="{{ article.image_set.all.0.image.url }}" style="width:auto; height:200px; border-radius:5px;">
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                         <!--    ниже пагинатор -->
                        {% if total > 1 %}
                            <div class="row" style="position: fixed;">
                                <nav aria-label="Page navigation example">
                                      <ul class="pagination">
                                          {% if articles.has_previous %}
                                            <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">Previous</a></li>
                                          {% endif %}
                                          {% for p in articles.paginator.page_range %}
                                            {% if articles.number == p %}
                                                <li class="page-item"><p class="page-link" style="color:black;"> {{ p }}</p></li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link" href="?page={{ p }}"> {{ p }}</a></li>
                                            {% endif %}
                                          {% endfor %}
                                          {% if articles.has_next %}
                                            <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">Next</a></li>
                                          {% endif %}
                                      </ul>
                                </nav>
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <div class="col content_center">
                    <div class="row">
                        <label><h1> Фильтры: (Всего :{{ total }} результатов) </h1>
                            <form class="d-flex" method="post">
                                {% csrf_token %}
                                <div class="form-group col-4">
                                    <select class="form-select" name="category_filter" style="width:40%">
                                        <option value="0">Все категории</option>
                                        {% for c in categories %}
                                            <option value="{{ forloop.counter }}" {% if selected_category == forloop.counter %} selected {% endif %}> {{ c.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <input type="submit" class="btn btn-success col-3" value="Применить">
                            </form>
                        </label>
                    </div>
                    <div class="row">
                        {% if request.user.is_superuser %}
                            <h1> Вы еще не написали ни одной новости. </h1>
                            <li><a class="ml-2" href="{% url 'news_input' %}"><h1> Хотите создать первую?</h1></a></li>
                        {% else %}
                            <h1> Вы еще не подали ни одной заявки. </h1>
                            <li><a class="ml-2" href="{% url 'news_request' %}"><h1> Хотите создать первую?</h1></a></li>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endblock %}
    </main>
    <script>
        let currentElem = null;
        main.onmouseover = function(event) {
          if (currentElem) return;
          let target = event.target.closest('li');
          if (!target) return;
          if (!main.contains(target)) return;
          currentElem = target;
          target.style.background = '#212529';
          target.style.color = '#FEDE00';
          target.style.boxShadow = "5px -5px 5px #212529, -5px 5px 5px #212529, -5px -5px 5px #212529, 5px 5px 5px #212529";
          target.style.fontWeight = '600';
          currentElem.style.transition = 'all 0.5s';
        };
        main.onmouseout = function(event) {
          if (!currentElem) return;
          let relatedTarget = event.relatedTarget;
          while (relatedTarget) {
            if (relatedTarget == currentElem) return;
            relatedTarget = relatedTarget.parentNode;
          }
          currentElem.style.background = '#5B5561';
          currentElem.style.color = '#E8C24D';
          currentElem.style.border = '';
          currentElem.style.boxShadow = '';
          currentElem.style.fontWeight = '400';
          currentElem.style.transition = 'all 0.5s';
          currentElem = null;
        };
    </script>
{% endblock %}